---
# general settings
default_username: ansible
dot_forward_email: hello@jimbalatero.com
private_key: .ssh/id_rsa
public_key: .ssh/id_rsa.pub
ntpserver: pool.ntp.org
timezone: UTC

# default sshd port
sshd_port: 22

# generate random passwords for default user and root user
default_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"
root_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"

# unattended packages install configuration
unattended_mail: "{{dot_forward_email}}"
unattended_remove_unused_dependencies: true
unattended_automatic_reboot_time: "03:00"
unattended_update_days: "Sat"
unattended_clean_interval: 7

control_node_ip: "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[0] }}"

# fail2ban
fail2ban_loglevel: INFO
fail2ban_destemail: "{{dot_forward_email}}"
# Ignore the control node ip
fail2ban_ignoreip: "127.0.0.1/8 {{control_node_ip}}"
fail2ban_mta: mail
fail2ban_services:
  - name: ssh
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log

# backports
# For some reason, https does not work
backports_uri: http://archive.ubuntu.com/ubuntu

# flag to install or skip docker module installation and configuration
install_docker: false
