---
# general settings
default_username: vagrant
dot_forward_email: hello@jimbalatero.com
private_key: .ssh/id_rsa
public_key: .ssh/id_rsa.pub
ntpserver: pool.ntp.org
timezone: UTC

# default sshd port
sshd_port: 22

# generate random passwords for default user and root user
default_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"
root_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"

# unattended packages install configuration
unattended_mail: "{{dot_forward_email}}"
unattended_remove_unused_dependencies: true
unattended_automatic_reboot_time: "03:00"
unattended_update_days: "Sat"
unattended_clean_interval: 7

# fail2ban
fail2ban_loglevel: INFO
fail2ban_services:
  - name: ssh
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log

php_version: '7.4'
php_enable_php_fpm: true
php_date_timezone: UTC
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "bayrunon.jimbalatero.com"
    documentroot: "/var/www/html"

certbot_create_if_missing: true
certbot_admin_email: "{{dot_forward_email}}"
certbot_create_standalone_stop_services:
  - apache

mailhog_version: 1.0.1
