---
php_version: '7.4'
php_mysql_package: "php{{php_version}}-mysql"
php_default_version_debian: "{{php_version}}"
php_fpm_daemon: "php{{php_version}}-fpm"
php_enable_php_fpm: true
php_date_timezone: UTC
apache_remove_default_vhost: true
apache_create_vhosts: false # we create our own

web_apps:
  - servername: "bayrunon.jimbalatero.com"
    serveradmin: "{{dot_forward_email}}"
    documentroot: "/var/www/bayrunon.jimbalatero.com/current/public"

  - servername: "phpmyadmin-bayrunon.jimbalatero.com"
    serveradmin: "{{dot_forward_email}}"
    documentroot: "/usr/share/phpmyadmin"

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - status.load
  - info.load

certbot_create_if_missing: false
certbot_auto_renew_options: "--apache --quiet --no-self-upgrade"

mailhog_version: 1.0.1
