---
php_version: '7.4'
php_enable_php_fpm: true
php_date_timezone: UTC
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "bayrunon.jimbalatero.com"
    serveradmin: "{{dot_forward_email}}"
    documentroot: "/var/www/html"
apache_vhosts_ssl:
  - servername: "bayrunon.jimbalatero.com"
    documentroot: "/var/www/html"
    serveradmin: "{{dot_forward_email}}"
    certificate_file: "/etc/letsencrypt/live/bayrunon.jimbalatero.com/fullchain.pem"
    certificate_key_file: "/etc/letsencrypt/live/bayrunon.jimbalatero.com/privkey.pem"
    certificate_chain_file: "/etc/letsencrypt/live/bayrunon.jimbalatero.com/chain.pem"
    extra_parameters: |
      <Location "/server-status">
          SetHandler server-status
          Require host bayrunon.jimbalatero.com
      </Location>

      <Location "/server-info">
          SetHandler server-info
          Require host bayrunon.jimbalatero.com
      </Location>

apache_mods_enabled:
    - rewrite.load
    - ssl.load
    - info.load
    - status.load

certbot_create_if_missing: true
certbot_admin_email: "{{dot_forward_email}}"
certbot_create_standalone_stop_services:
  - apache
certbot_certs:
  - email: "{{dot_forward_email}}"
    domains:
      - bayrunon.jimbalatero.com

mailhog_version: 1.0.1
