---
# Local LAN IP-range addresses
local_lan: "192.168.0.0/16"

# ufw rules
ufw_rules:
  - {rule: allow, port: "{{sshd_port}}", src: "{{local_lan}}", proto: tcp, direction: "in"}
  # Uncomment this to only allow ssh access through control node server, and comment the next below
  # - {rule: allow, port: "{{sshd_port}}", src: "{{control_node_ip}}", proto: tcp, direction: "in"}
  # For now, allow port "{{sshd_port}}" for all.
  - {rule: allow, port: "{{sshd_port}}", src: "0.0.0.0/0", proto: tcp, direction: "in"}
  # mysql
  - { rule: allow, port: 3306, src: "0.0.0.0/0", proto: tcp, direction: "in" }
  # monit
  - {rule: allow, port: 2812, src: "0.0.0.0/0", proto: tcp, direction: "in"}
  # http
  - {rule: allow, port: 80, src: "0.0.0.0/0", proto: tcp, direction: "in"}
  # https
  - {rule: allow, port: 443, src: "0.0.0.0/0", proto: tcp, direction: "in"}
  # mailhog
  - {rule: allow, port: 8025, src: "0.0.0.0/0", proto: tcp, direction: "in"}
  # smtp
  - {rule: allow, port: "{{smtp_port}}", src: "any", proto: tcp, direction: "out"}

# network configuration for our server
interfaces_template: "interfaces-dhcp-server.j2"
