---
- hosts: prod
  vars_files:
    - group_vars/all.yml
    - group_vars/apt.yml
    - group_vars/monit.yml
    - group_vars/networking.yml
    - group_vars/vault.yml
    - group_vars/lamp-server.yml
  user: "{{default_username}}"  # run whole script with default user
  become: yes
  roles:  # order is not random!
    - role: nickjj.fail2ban
      tags: fail2ban
    - role: common
      tags: common
    - role: jnv.unattended-upgrades
      tags: common
    - role: ufw
      tags: ufw
    - role: user
      tags: user
    - role: ssh
      tags: ssh
    - role: geerlingguy.apache
      tags: [ lamp-sever, apache ]
    - role: geerlingguy.certbot
      tags: [ lamp-sever, apache, certbot ]

    - name: Install Web-App
      with_items: "{{ web_apps }}"
      tags: [ lamp-sever, apache, web-app ]
      include_role:
        name: web_app
      loop_control:
        loop_var: app

    - role: geerlingguy.php-versions
      tags: [ lamp-sever, php ]
    - role: geerlingguy.php
      tags: [ lamp-sever, php ]
    - role: geerlingguy.php-xdebug
      tags: [ lamp-sever, php ]
    - role: geerlingguy.php-mysql
      tags: [ lamp-sever, php ]
    - role: geerlingguy.php-redis
      tags: [ lamp-sever, php ]
    - role: geerlingguy.php-pecl
      tags: [ lamp-sever, php ]
    - role: geerlingguy.apache-php-fpm
      tags: [ lamp-sever, php ]
    - role: geerlingguy.composer
      tags: [ lamp-sever, php ]
    - role: geerlingguy.mysql
      tags: [ lamp-sever, db ]
    - role: geerlingguy.phpmyadmin
      tags: [ lamp-sever, db ]
    - role: geerlingguy.redis
      tags: redis
    - role: geerlingguy.mailhog
      tags: mailhog
    - role: ansible-monit
      tags: monit
