---
- hosts: prod
  vars_files:
    - group_vars/all.yml
    - group_vars/apt.yml
    - group_vars/monit.yml
    - group_vars/networking.yml
    - group_vars/vault.yml
    - group_vars/lamp-server.yml
  user: "{{default_username}}"  # run whole script with default user
  become: yes
  roles:  # order is not random!
    - role: nickjj.fail2ban
      tags: fail2ban
    - role: common
      tags: common
    - role: jnv.unattended-upgrades
      tags: common
    - role: ufw
      tags: ufw
    - role: user
      tags: user
    - role: ssh
      tags: ssh
    - role: geerlingguy.apache
      tags: [ lamp-server, apache ]
    - role: apache-bad-bot-blocker
      tags: [ lamp-server, apache, bad-bot-blocker ]
    - role: geerlingguy.php-versions
      tags: [ lamp-server, php ]
    - role: geerlingguy.php
      tags: [ lamp-server, php ]
    - role: geerlingguy.php-xdebug
      tags: [ lamp-server, php ]
    - role: geerlingguy.php-mysql
      tags: [ lamp-server, php ]
    - role: geerlingguy.php-redis
      tags: [ lamp-server, php ]
    - role: geerlingguy.php-pecl
      tags: [ lamp-server, php ]
    - role: geerlingguy.apache-php-fpm
      tags: [ lamp-server, php ]
    - role: geerlingguy.composer
      tags: [ lamp-server, php ]
    - role: geerlingguy.certbot
      tags: [ lamp-sever, apache, certbot ]
    - role: web_app
      tags: [ lamp-sever, apache, web_app ]
    - role: geerlingguy.mysql
      tags: [ lamp-server, db ]
    - role: geerlingguy.phpmyadmin
      tags: [ lamp-server, db ]
    - role: geerlingguy.redis
      tags: redis
    - role: geerlingguy.mailhog
      tags: mailhog
    - role: ansible-monit
      tags: monit
