---
- hosts: prod
  vars_files:
    - group_vars/all.yml
    - group_vars/apt.yml
    - group_vars/docker.yml
    - group_vars/monit.yml
    - group_vars/networking.yml
    - group_vars/vault.yml
    - group_vars/lamp-server.yml
    - group_vars/mysql.yml
  user: "{{default_username}}"  # run whole script with default user
  become: yes
  roles:  # order is not random!
    - role: nickjj.fail2ban
      tags: fail2ban
    - role: common
      tags: common
    - role: ufw
      tags: ufw
    - role: user
      tags: user
    - role: ssh
      tags: ssh
    - role: jnv.debian-backports
      tags: common
    - role: jnv.unattended-upgrades
      tags: common
    - role: geerlingguy.apache
      tags: lamp-server
    - role: geerlingguy.php-versions
      tags: lamp-server
    - role: geerlingguy.php
      tags: lamp-server
    - role: geerlingguy.php-xdebug
      tags: lamp-server
    - role: geerlingguy.php-mysql
      tags: lamp-server
    - role: geerlingguy.php-redis
      tags: lamp-server
    - role: geerlingguy.php-pecl
      tags: lamp-server
    - role: geerlingguy.apache-php-fpm
      tags: lamp-server
    - role: geerlingguy.certbot
      tags: certbot
    - role: geerlingguy.composer
      tags: lamp-server
    - role: geerlingguy.mysql
      tags: lamp-server-db
      become: yes
    - role: geerlingguy.phpmyadmin
      tags: lamp-server-db
    - role: geerlingguy.redis
      tags: redis
    - role: geerlingguy.mailhog
      tags: for-development
    - role: ansible-monit
      tags: common
