---
- src: nickjj.fail2ban
- src: nickjj.docker
- src: https://github.com/mrlesmithjr/ansible-monit
- src: jnv.debian-backports
- src: jnv.unattended-upgrades
- src: geerlingguy.apache
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.certbot
- src: geerlingguy.mysql
- src: geerlingguy.redis
- src: geerlingguy.php-mysql
- src: geerlingguy.php-redis
- src: geerlingguy.php-xdebug
- src: geerlingguy.php-pecl
- src: geerlingguy.composer
- src: geerlingguy.mailhog
- src: geerlingguy.phpmyadmin
- src: geerlingguy.nodejs
