---
apache_vhosts:
  - servername: "{{ app.servername }}"
    serveradmin: "{{dot_forward_email}}"
    documentroot: "{{ app.documentroot }}"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ documentroot }}"
      ErrorLog {{ app.logs_dir }}/apache2/error.log
      CustomLog {{ app.logs_dir }}/apache2/access.log combined

apache_vhosts_ssl:
  - servername: "{{ app.servername }}"
    documentroot: "{{ app.documentroot }}"
    serveradmin: "{{dot_forward_email}}"
    certificate_file: "/etc/letsencrypt/live/{{ app.servername }}/fullchain.pem"
    certificate_key_file: "/etc/letsencrypt/live/{{ app.servername }}/privkey.pem"
    certificate_chain_file: "/etc/letsencrypt/live/{{ app.servername }}/chain.pem"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ documentroot }}"
      ErrorLog {{ app.logs_dir }}/apache2/error.log
      CustomLog {{ app.logs_dir }}/apache2/access.log combined
