- name: Install collectd
  apt: pkg=collectd state=present

- name: Copy collectd configuration file into place
  template: src=etc_collectd_collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify: restart collectd

- name: Ensure collectd is started
  service: name=collectd state=started

# Work around https://github.com/ansible/ansible-modules-core/issues/915
# otherwise we'd use enabled=yes in previous task
- name: Ensure collectd is enabled
  command: update-rc.d collectd enable creates=/etc/rc3.d/S03collectd

- name: Add mail_count in types.db
  lineinfile:
    dest: /usr/share/collectd/types.db
    state: present
    line: "mail_count              value:COUNTER:0:65535"
    insertafter: "EOF"
  notify: restart collectd

- name: Add exim filter
  blockinfile:
    path: /etc/collectd/collectd.conf.d/filters.conf
    block: |
      PreCacheChain "PreCache"
      LoadPlugin match_regex
      LoadPlugin target_scale

      <Chain "PreCache">
          <Rule>
              <Match "regex">
                  Plugin "^tail$"
                  PluginInstance "^exim$"
                  Type "^mail_count$"
                  Invert false
              </Match>
              <Target "scale">
                  Factor 60
              </Target>
          </Rule>
      </Chain>
  notify: restart collectd
  tags:
    - exim-filter-collectd
