- name: Install collectd
  apt: pkg=collectd state=present

- name: Copy collectd configuration file into place
  template: src=etc_collectd_collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify: restart collectd

- name: Ensure collectd is started
  service: name=collectd state=started

# Work around https://github.com/ansible/ansible-modules-core/issues/915
# otherwise we'd use enabled=yes in previous task
- name: Ensure collectd is enabled
  command: update-rc.d collectd enable creates=/etc/rc3.d/S03collectd

- name: Add mail_count in types.db
  lineinfile:
    dest: /usr/share/collectd/types.db
    state: present
    line: "mail_count              value:COUNTER:0:65535"
    insertafter: "EOF"
  notify: restart collectd

- name: Add exim filter
  blockinfile:
    path: /etc/collectd/collectd.conf.d/filters.conf
    block: |
      PreCacheChain "PreCache"
      LoadPlugin match_regex
      LoadPlugin target_scale

      <Chain "PreCache">
          <Rule>
              <Match "regex">
                  Plugin "^tail$"
                  PluginInstance "^exim$"
                  Type "^mail_count$"
                  Invert false
              </Match>
              <Target "scale">
                  Factor 60
              </Target>
          </Rule>
      </Chain>
  notify: restart collectd
  tags:
    - exim-filter-collectd

- name: Enable php-fpm status
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    regexp: "^;pm.status_path"
    line: "pm.status_path = /php_fpm_status"
    state: present
  notify: restart php-fpm
  tags:
    - php-fpm

- name: Enable apache php-fpm config
  file:
    src: "/etc/apache2/conf-available/{{ item }}"
    dest: "/etc/apache2/conf-enabled/{{ item }}"
    state: link
    mode: 0644
  notify: restart apache2
  tags:
    - php-fpm

- name: Configure php-fpm status
  blockinfile:
    path: /etc/apache2/conf-available/php{{ php_version }}-fpm.conf
    block: |
      <LocationMatch "/php_fpm_status">
          Require ip 127.0.0.1
          SetHandler "proxy:fcgi://127.0.0.1:9000"
      </LocationMatch>
    state: present
  notify: restart php-fpm
  tags:
    - php-fpm

- name: Enable php-fpm slow logging
  lineinfile:
    dest: /etc/php/{{php_version }}/fpm/pool.d/www.conf
    regexp: "^;slowlog"
    line: "slowlog = /var/log/php7.4-fpm.$pool.log.slow"
    state: present
  notify: restart php-fpm
  tags:
    - php-fpm

- name: Change php-fpm slow logging timeout
  lineinfile:
    dest: /etc/php/{{php_version }}/fpm/pool.d/www.conf
    regexp: "^;request_slowlog_timeout"
    line: "request_slowlog_timeout = 3s"
    state: present
  notify: restart php-fpm
  tags:
    - php-fpm
