---
- name: Install facette/facette
  apt:
    deb: https://github.com/facette/facette/releases/download/0.5.1/facette_0.5.1_bionic-amd64.deb

- name: Ensure facette starts on a fresh reboot
  service: name=facette state=started enabled=yes

- name: Enable HTTP for public access
  replace:
    path: /etc/facette/facette.yaml
    regexp: localhost:12003 #default
    replace: 0.0.0.0:{{ facette_port }}
  notify: restart facette

- name: Set default time range
  replace:
    path: /etc/facette/facette.yaml
    regexp: "time_range: -1h"
    replace: "time_range: -24h"
  notify: restart facette

- name: Add RRD provider
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/providers
    body: "{{ add_rrd_provider_json }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Memory Usage Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ item }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  with_items:
    - "{{ add_graph_memory_usage }}"
    - "{{ add_graph_load_avgs }}"
    - "{{ add_graph_apache_bytes }}"
    - "{{ add_graph_apache_connections }}"
    - "{{ add_graph_apache_idle_workers }}"
    - "{{ add_graph_apache_requests }}"
    - "{{ add_graph_apache_scoreboard }}"
  tags:
    - init-config-facette
