---
- name: Install facette/facette
  apt:
    deb: https://github.com/facette/facette/releases/download/0.5.1/facette_0.5.1_bionic-amd64.deb

- name: Enable HTTP for public access
  replace:
    path: /etc/facette/facette.yaml
    regexp: localhost:12003 #default
    replace: 0.0.0.0:{{ facette_port }}
  notify: restart facette

- name: Set default time range
  replace:
    path: /etc/facette/facette.yaml
    regexp: "time_range: -1h"
    replace: "time_range: -24h"
  notify: restart facette

- name: Add RRD provider
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/providers
    body: "{{ add_rrd_provider_json }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Memory Usage Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_memory_usage }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Load Averages Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_load_avgs }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Apache Bytes Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_apache_bytes }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Apache Connections Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_apache_connections }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Apache Idle Workers Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_apache_idle_workers }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Apache Requests Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_apache_requests }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette

- name: Add Apache Scoreboard Graph
  uri:
    url: http://localhost:{{ facette_port }}/api/v1/library/graphs
    body: "{{ add_graph_apache_scoreboard }}"
    body_format: json
    status_code: [201, 409]
    method: POST
    return_content: yes
  tags:
    - init-config-facette
