---
- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart cron
  service:
    name: cron
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart exim4
  service:
    name: exim4
    state: restarted

- name: newaliases
  command: newaliases
