---
- name: Download update-apacheblocker.sh
  get_url:
    url: https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/update-apacheblocker.sh
    dest: /usr/sbin/update-apacheblocker.sh
    mode: 0755

- name: Change email for notification
  lineinfile:
    dest: /usr/sbin/update-apacheblocker.sh
    state: present
    regexp: "^#?EMAIL="
    line: "EMAIL='{{dot_forward_email}}'"

- name: Add cron job for apache blocker updater
  cron:
    name: Apache blocker updater
    job: /usr/sbin/update-apacheblocker.sh
    special_time: daily
    state: present
