---
- name: Check if vhost {{ app.servername }} already exists.
  stat:
    path: "{{ apache_conf_path }}/sites-available/{{ app.servername }}.conf"
  register: app_stat

- name: Create a apache2 logs directory if it does not exist
  file:
    path: "{{ app.logs_dir }}/apache2"
    state: directory
    mode: '0755'

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ app.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: not app_stat.stat.exists
