---
- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "/etc/apache2/sites-available/{{ app.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Create a apache2 logs directory if it does not exist
  file:
    path: "{{ app.logs_dir }}/apache2"
    state: directory
    mode: '0755'
