---
- name: Add apache vhosts configuration for {{app.servername}}.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ app.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
